import dotenv from 'dotenv'
import mongoose from 'mongoose'
import Vehicle from './src/models/Vehicle'

dotenv.config()

const vehicles = [
  {
    make: 'Hyundai',
    model: 'Creta',
    category: 'SUV',
    price: 1090700,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: '17.4 km/l',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/creta/1.png',
  },
  {
    make: 'Tata',
    model: 'Nexon',
    category: 'SUV',
    price: 736000,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: '17.0 km/l',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/nexon/1.png',
  },
  {
    make: 'Tata',
    model: 'Nexon EV',
    category: 'SUV',
    price: 1249000,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: 'Up to 489 km range',
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/nexon-ev/1.png',
  },
  {
    make: 'Toyota',
    model: 'Innova Hycross',
    category: 'MPV',
    price: 1870000,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: 'Up to 23.24 km/l',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'MPV',
    location: 'Hyderabad',
    image: '/cars/innova-hycross/1.png',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Grand Vitara',
    category: 'SUV',
    price: 1080000,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: 'Up to 27.97 km/l',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/grand-vitara/1.png',
  },
  {
    make: 'Kia',
    model: 'Seltos',
    category: 'SUV',
    price: 1099000,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: 'Up to 20.8 km/l',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/seltos/1.png',
  },
  {
    make: 'Mahindra',
    model: 'Scorpio-N',
    category: 'SUV',
    price: 1370000,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: 'Up to 15.4 km/l',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/scorpio-n/1.png',
  },
  {
    make: 'Toyota',
    model: 'Fortuner',
    category: 'SUV',
    price: 3695000,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: '14.4 km/l',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/fortuner/1.png',
  },
  {
    make: 'Hyundai',
    model: 'i20',
    category: 'Hatchback',
    price: 729000,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: 'Up to 20.0 km/l',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'Hatchback',
    location: 'Hyderabad',
    image: '/cars/i20/1.png',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Baleno',
    category: 'Hatchback',
    price: 599900,
    quantity: 5,
    year: 2026,
    condition: 'New',
    mileage: 'Up to 22.35 km/l',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'Hatchback',
    location: 'Hyderabad',
    image: '/cars/baleno/1.png',
  },
  {
    make: 'Honda',
    model: 'City',
    category: 'Sedan',
    price: 1190000,
    quantity: 3,
    year: 2023,
    condition: 'Used',
    mileage: '17.8 km/l',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    location: 'Hyderabad',
    image: '/cars/city/1.png',
  },
  {
    make: 'Honda',
    model: 'Civic',
    category: 'Sedan',
    price: 1680000,
    quantity: 3,
    year: 2022,
    condition: 'Used',
    mileage: '16.5 km/l',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    location: 'Hyderabad',
    image: '/cars/civic/1.png',
  },
  {
    make: 'Toyota',
    model: 'Fortuner',
    category: 'SUV',
    price: 3150000,
    quantity: 3,
    year: 2022,
    condition: 'Used',
    mileage: '14.2 km/l',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/fortuner/1.png',
  },
  {
    make: 'Tata',
    model: 'Harrier',
    category: 'SUV',
    price: 1890000,
    quantity: 3,
    year: 2024,
    condition: 'Used',
    mileage: '16.8 km/l',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/harrier/1.png',
  },
  {
    make: 'Hyundai',
    model: 'Creta',
    category: 'SUV',
    price: 1375000,
    quantity: 3,
    year: 2023,
    condition: 'Used',
    mileage: '21.4 km/l',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/creta/1.png',
  },
  {
    make: 'BMW',
    model: '3 Series',
    category: 'Sedan',
    price: 4650000,
    quantity: 2,
    year: 2023,
    condition: 'Used',
    mileage: '16.1 km/l',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    location: 'Hyderabad',
    image: '/cars/bmw-3-series/1.png',
  },
  {
    make: 'Ford',
    model: 'Mustang',
    category: 'Coupe',
    price: 5900000,
    quantity: 2,
    year: 2022,
    condition: 'Used',
    mileage: '10.2 km/l',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Coupe',
    location: 'Hyderabad',
    image: '/cars/mustang/1.png',
  },
  {
    make: 'MG',
    model: 'ZS EV',
    category: 'SUV',
    price: 1850000,
    quantity: 3,
    year: 2024,
    condition: 'Used',
    mileage: 'Up to 461 km range',
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/zs-ev/1.png',
  },
  {
    make: 'Toyota',
    model: 'Camry',
    category: 'Sedan',
    price: 3650000,
    quantity: 2,
    year: 2024,
    condition: 'Used',
    mileage: 'Up to 25.49 km/l',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    location: 'Hyderabad',
    image: '/cars/camry/1.png',
  },
  {
    make: 'Maruti Suzuki',
    model: 'Grand Vitara',
    category: 'SUV',
    price: 1425000,
    quantity: 3,
    year: 2024,
    condition: 'Used',
    mileage: 'Up to 27.97 km/l',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    location: 'Hyderabad',
    image: '/cars/grand-vitara/1.png',
  },
]

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI as string)

    await Vehicle.deleteMany({})

    await Vehicle.insertMany(vehicles)

    console.log(`Successfully inserted ${vehicles.length} vehicles`)

    await mongoose.disconnect()
  } catch (error) {
    console.error('Seed failed:', error)
    process.exit(1)
  }
}

seed()
